// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.17.3
// source: proto/frequency/frequency.proto

package frequency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_frequency_frequency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frequency_frequency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_proto_frequency_frequency_proto_rawDescGZIP(), []int{0}
}

func (x *InputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type OutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[string]int64 `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_frequency_frequency_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frequency_frequency_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_proto_frequency_frequency_proto_rawDescGZIP(), []int{1}
}

func (x *OutputResponse) GetResult() map[string]int64 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_frequency_frequency_proto protoreflect.FileDescriptor

var file_proto_frequency_frequency_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x2f, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x22, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x8f, 0x01, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x5f,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x39, 0x0a, 0x0b,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x5c, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x64, 0x46,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x4b, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x66, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x78, 0x61, 0x6e, 0x6b, 0x69, 0x74, 0x2f, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2f,
	0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_frequency_frequency_proto_rawDescOnce sync.Once
	file_proto_frequency_frequency_proto_rawDescData = file_proto_frequency_frequency_proto_rawDesc
)

func file_proto_frequency_frequency_proto_rawDescGZIP() []byte {
	file_proto_frequency_frequency_proto_rawDescOnce.Do(func() {
		file_proto_frequency_frequency_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_frequency_frequency_proto_rawDescData)
	})
	return file_proto_frequency_frequency_proto_rawDescData
}

var file_proto_frequency_frequency_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_frequency_frequency_proto_goTypes = []interface{}{
	(*InputRequest)(nil),   // 0: word_frequency.inputRequest
	(*OutputResponse)(nil), // 1: word_frequency.outputResponse
	nil,                    // 2: word_frequency.outputResponse.ResultEntry
}
var file_proto_frequency_frequency_proto_depIdxs = []int32{
	2, // 0: word_frequency.outputResponse.result:type_name -> word_frequency.outputResponse.ResultEntry
	0, // 1: word_frequency.WordFrequency.Calculate:input_type -> word_frequency.inputRequest
	1, // 2: word_frequency.WordFrequency.Calculate:output_type -> word_frequency.outputResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_frequency_frequency_proto_init() }
func file_proto_frequency_frequency_proto_init() {
	if File_proto_frequency_frequency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_frequency_frequency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_frequency_frequency_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_frequency_frequency_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_frequency_frequency_proto_goTypes,
		DependencyIndexes: file_proto_frequency_frequency_proto_depIdxs,
		MessageInfos:      file_proto_frequency_frequency_proto_msgTypes,
	}.Build()
	File_proto_frequency_frequency_proto = out.File
	file_proto_frequency_frequency_proto_rawDesc = nil
	file_proto_frequency_frequency_proto_goTypes = nil
	file_proto_frequency_frequency_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WordFrequencyClient is the client API for WordFrequency service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordFrequencyClient interface {
	Calculate(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error)
}

type wordFrequencyClient struct {
	cc grpc.ClientConnInterface
}

func NewWordFrequencyClient(cc grpc.ClientConnInterface) WordFrequencyClient {
	return &wordFrequencyClient{cc}
}

func (c *wordFrequencyClient) Calculate(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error) {
	out := new(OutputResponse)
	err := c.cc.Invoke(ctx, "/word_frequency.WordFrequency/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordFrequencyServer is the server API for WordFrequency service.
type WordFrequencyServer interface {
	Calculate(context.Context, *InputRequest) (*OutputResponse, error)
}

// UnimplementedWordFrequencyServer can be embedded to have forward compatible implementations.
type UnimplementedWordFrequencyServer struct {
}

func (*UnimplementedWordFrequencyServer) Calculate(context.Context, *InputRequest) (*OutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}

func RegisterWordFrequencyServer(s *grpc.Server, srv WordFrequencyServer) {
	s.RegisterService(&_WordFrequency_serviceDesc, srv)
}

func _WordFrequency_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordFrequencyServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word_frequency.WordFrequency/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordFrequencyServer).Calculate(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordFrequency_serviceDesc = grpc.ServiceDesc{
	ServiceName: "word_frequency.WordFrequency",
	HandlerType: (*WordFrequencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _WordFrequency_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/frequency/frequency.proto",
}
